### ISSUE TITLE
Cannot rename a new folder if the English language is selected

### ISSUE THREAD

**Issue by mp4096** [mediatum/mediatum#2]
How to reproduce:
* Select the English site version
* Create a new folder somewhere in the mediaTUM tree
* Right-click and rename it
* Enter a new name in the first field (`Folder name`)
* Click on `Save`.
* :boom: Nothing happens; after page reload, the folder is still named `New folder`

Now change the language to German and repeat the steps above. The folder is renamed sucessfully.

Tested in Chromium 55.0.2883.87 and Pale Moon 27.0.3 (x64) running on Ubuntu 16.04.

**Comment by czam-tum** [comment]
Thank you very much for this detailed analysis and report of this issue. We could reproduce it and it we expect it to be fixed in the upcoming release v2017.02.

**Comment by mp4096** [comment]
It works now, thanks!
