### ISSUE TITLE
Can't login with default setup

### ISSUE THREAD

**Issue by BenediktSeidl** [mediatum/mediatum#3]
I just followed the [Quick Test Installation In Three Steps](/mediatum/mediatum/#quick-test-installation-in-three-steps) but can not login with the provided credentials (admin - insecure), although the log says:

```
2017-01-14 16:36:21,937 [23735/Dummy-2] core.auth INFO | internal auth succeeded for login name admin
2017-01-14 16:36:21,938 [23735/Dummy-2] web.frontend.login INFO | admin logged in
```

The problem seems to be, that the cookie is secure, but the server is plaintext. I just fixed it by changing the default:

```diff
diff --git a/core/athana.py b/core/athana.py
index cb55ecc..5ca0e0d 100644
--- a/core/athana.py
+++ b/core/athana.py
@@ -1050,7 +1050,7 @@ class http_request(object):
             close_it = 1
 
         if self.session and "PSESSION" not in self.Cookies:
-            self.setCookie('PSESSION', self.sessionid, path="/", secure=config.getboolean("host.ssl", True))
+            self.setCookie('PSESSION', self.sessionid, path="/", secure=config.getboolean("host.ssl", False))
             
         if "Cache-Control" not in self.reply_headers or not config.getboolean("athana.allow_cache_header", False):
             self.reply_headers["Cache-Control"] = "no-cache"
```

Copying the config as said in `INSTALL.md` also does not fix the problem as there is no default value for `host.ssl` in `mediatum.cfg.template`.

**Comment by czam-tum** [comment]
Thank you for the detailed description. We solved this issue in the same way by changing the default value and the fix will be included in v2017.01.
